---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace home-automation

helmCharts:
  - name: emqx
    repo: https://repos.emqx.io/charts
    version: 5.8.8
    releaseName: emqx
    namespace: *namespace
    valuesFile: values.yaml
