---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace media

resources:
  - immich-library-v4.yaml
  - immich-ml-cache-v3.yaml
  - immich-cnpg-cluster.yaml

generators:
  - ksops.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.4.0
    releaseName: immich-server
    namespace: *namespace
    valuesFile: values-server.yaml
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.4.0
    releaseName: immich-machine-learning
    namespace: *namespace
    valuesFile: values-machine-learning.yaml
  # - name: redis
  #   repo: https://ot-container-kit.github.io/helm-charts
  #   version: 0.16.8
  #   releaseName: immich-redis
  #   namespace: *namespace
  #   valuesFile: values-redis.yaml
