---
# Redis Standalone Configuration for Immich
# Ref: https://github.com/OT-CONTAINER-KIT/redis-operator/tree/main/charts/redis

# Storage configuration
storageSpec:
  volumeClaimTemplate:
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn-nvme-3-replicas
      resources:
        requests:
          storage: 200Mi

# FIXME: this is a hack to make sure that redisConfig is rendered properly,
# and not assigned to 'null', which was preventing ArgoCD from syncing.
externalConfig:
  enabled: true
  data: ""

# Enable Redis exporter for Prometheus monitoring
redisExporter:
  enabled: true

# Enable ServiceMonitor for Prometheus
serviceMonitor:
  enabled: true
