---
# Redis Standalone Configuration for Immich
# Ref: https://github.com/OT-CONTAINER-KIT/redis-operator/tree/main/charts/redis

# Storage configuration
storageSpec:
  volumeClaimTemplate:
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn-nvme-3-replicas
      resources:
        requests:
          storage: 200Mi

# FIXME: re-enable after deploying prometheus
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

# Enable Redis exporter for Prometheus monitoring
redisExporter:
  enabled: false

# Enable ServiceMonitor for Prometheus
serviceMonitor:
  enabled: false
