---
controller:
  service:
    externalTrafficPolicy: Local # To preserve the original client IP address.
    annotations:
      # Fixes the IP of the Ingress Controller; we should expose 80 and 443 on this IP.
      metallb.io/loadBalancerIPs: 10.0.3.1

  metrics:
    enabled: true
    serviceMonitor: { enabled: true }
