---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace auth

resources:
  - authelia-cnpg-cluster.yaml
  - ingress.yaml

generators:
  - ksops.yaml

helmCharts:
  - name: authelia
    repo: https://charts.authelia.com
    version: 0.10.49
    releaseName: authelia
    namespace: *namespace
    valuesFile: values-authelia.yaml
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.5.0
    releaseName: authelia-proxy
    namespace: *namespace
    valuesFile: values-proxy.yaml
  - name: redis
    repo: https://ot-container-kit.github.io/helm-charts
    version: 0.16.8
    releaseName: authelia-redis
    namespace: *namespace
    valuesFile: values-redis.yaml
