# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace networking

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.19.0
    releaseName: external-dns-cloudflare
    namespace: *namespace
    valuesFile: values-cloudflare.yaml
