---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace metallb-system

resources:
  - metallb-pool.yaml
  - k8s-pool.yaml
  - l2-advertisement.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.15.2
    releaseName: metallb
    namespace: *namespace
    includeCRDs: true
    valuesInline:
      speaker:
        frr:
          enabled: true
