---
ingress:
  enabled: true
  ingressClassName: tailscale
  hosts:
    - host: &host nl-z2m
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - *host

service:
  type: ClusterIP

statefulset:
  resources:
    requests:
      akri.sh/sonoff-zigbee-antenna: "1"
    limits:
      akri.sh/sonoff-zigbee-antenna: "1"
  storage:
    enabled: true
    storageClassName: longhorn-nvme-3-replicas
    size: 200M

zigbee2mqtt:
  permit_join: true
  mqtt:
    server: mqtt://mochi-mqtt.home-automation.svc.cluster.local:1883
    version: 5
  serial:
    port: /dev/ttyUSB0
    adapter: ezsp # Sonoff dongle is based on Silicon Labs.
  availability:
    enabled: true
    # Time after which an active device will be marked as offline in
    # minutes (default = 10 minutes)
    active: { timeout: 2 }
    # Time after which a passive device will be marked as offline in
    # minutes (default = 1500 minutes aka 25 hours)
    passive: { timeout: 1500 }
