---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace auth

resources:
  - persistentvolumeclaims.yaml

generators:
  - ksops.yaml
# helmCharts:
#   - name: vaultwarden
#     repo: https://gissilabs.github.io/charts
#     version: 1.3.0
#     releaseName: vaultwarden
#     namespace: *namespace
#     valuesFile: values.yaml
