# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: esphome-secrets
    namespace: home-automation
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:XLQr3oq9Ms1KP8GTp1RutAKvZM58m07iH9YGreQ37SYqoTnZVCoigvcrjQLF84WhtC5OOLVbCRskzWTtXvxnWmncmMh9hFCKt7E56JabwdEs6cJ0VdjCF9LdlTx1ePC41ssSfkw+JfFa5po0ZBwd0IAE7mfZjo2h0NomSemC,iv:EyrfadcUpIszutMin4PTKtuaappDhMGDmfSMtng2DzA=,tag:7sg0qhW/xdzrdGrbBJU4eA==,type:str]
sops:
    age:
        - recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS25xaUNqL0RKM0wrNk9v
            NXdRTTN3UE5nWWZjcjBRWkF1VzlNZVRzdEdVCmVZRkU0VlpSNGF4NmxiTXl2ZTdr
            WkZTa1piMFJPbU4ybVM5WkpDTENWa0kKLS0tIEp1NE40d3RQTHJVTTNpUk9BRmYx
            OVFOVytqRDI4dVRoQld1Y1pzZVRCTlEKVpPzPNO8ufFneIIlPSafJ2TEa0nlek6q
            ArDefTQQd8suzaQVZJwwMlHJxtgdKhFx8YkkEfoH9qCgrKygaOQPSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T08:55:18Z"
    mac: ENC[AES256_GCM,data:3dAiImgW1x2M69pJot7E6urnfNgxjO39K+AnAbTm+b0TJsJCm1YTRqtiFGa77F59QssfBHLu3D7UwAi2mW4YonpHc0E9jeKa3KMJmHteLCujPf6xbjfnaypX6TSS3gY1q484sI6ksGEPm5CRA4wbBk3IX71ZENvtHtIuTb/2iRw=,iv:Ra2XIzF8GWNDGKyZi9Cy8wEsf1g7b9jGtwYINGJfGHA=,tag:K8wsUkCRiPefsD+fhorKOw==,type:str]
    pgp:
        - created_at: "2025-11-27T08:55:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf/XNOMEQTcxRz2OhNrj19oSURD1ZbsLvXKTKMt5MUCc8pd
            sWFmUpfQ7lXrtPt9ru4vPn0vms62xyzaA5Cby8Wvqb/wP45My/CxpxVzy94NGBUl
            6TU4YvNlvaWOTW2kbyRGuGFTwq3f8dSOd8Ry8eO1bGw2FN6gM4nDyiJZmsLtfysb
            j0/gRXa8eay36rE6QYSsKTviBMYwIlg5piSqrmgDs34NqMEyKMjNb9K3m5qT+jb/
            XNucCfyLOS3C5kz4dAe7505+06GbuBcswMj79LUtkrbu4z6CpMAozXOiC/ZRcVOK
            iENUT7UrJQvbiiRJjSKBuK+GHdkEGwhdMQ8dJLwHEgf9FwXIblPQ1jwCM4aUQa5E
            7he2vDTJY8xGWhDXi9wNGNDSoM2gZJM0BMuskjGz+qYKfYhbzIX++kn7rXco57xz
            NVbCZJoPmy1FxFHRbYIoAffUT7dAQvrDkifY9YLouXkGseVXW4i0L5TuoIfKcGik
            1VxmWe1l/xUufWm5jUU4f21AiOujct1eERZDXM14F2baqY7tv8wiLDFx+pmSB8D/
            hggcno5h3vAyVJCnDf85Nw5vLcx/IKPvOUo+ARmf4sYGonH28IwlEkmgjZu9O4/o
            m0G6eyDZ2KBDyffRvd6Y3pGXcwGMs5NFJmtOlw3+LfBn2J46de3PupLbLI5ozM/9
            BNJcAVPYjWoiWv81NDDD9eLjyN3nlTYDEdOQJBqG1cMKZCXTKeNou/eFD2Ogad9W
            ZiRKQL/KZu1obdcPgqCEli4z1MGjDIFN8m3Irh6GqDlNY1meznc6vwTH3qqXdb0=
            =Z6Sn
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
