---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: esphome-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./esphome-secrets.enc.yaml
