---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace home-automation

resources:
  - persistentvolumeclaims.yaml

generators:
  - ksops.yaml

configMapGenerator:
  - name: home-assistant-configuration
    namespace: *namespace
    files:
      - ./config/configuration.yaml
      - ./config/scenes.yaml
      - ./config/scripts.yaml
  - name: home-assistant-automations
    namespace: *namespace
    files:
      - ./automations/home.yaml
      - ./automations/kitchen.yaml
      - ./automations/litter-robot.yaml
      - ./automations/toilet.yaml
      - ./automations/vacuum.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
    releaseName: home-assistant
    namespace: *namespace
    valuesFile: values.yaml
