---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/values.schema.json
defaultPodOptions:
  hostNetwork: true # Required for certain network features.
  # NOTE: seems like this doesn't play well with custom components sadly...
  # securityContext:
  #   runAsUser: 1000
  #   runAsGroup: 1000
  #   fsGroup: 1000
  #   fsGroupChangePolicy: "OnRootMismatch"

controllers:
  main:
    type: deployment
    replicas: 0
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: "2026.1.0"
        env:
          TZ: Europe/Amsterdam
          PYTHONPATH: /config/deps
          UV_SYSTEM_PYTHON: "true"
          UV_NO_CACHE: "true"
        envFrom:
          - secretRef:
              name: home-assistant-oauth-secrets
        probes:
          # FIXME(ar3s3ru): find a way to enable these?
          liveness: { enabled: false }
          readiness: { enabled: false }
          startup: { enabled: true }

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8123

ingress:
  tailscale:
    enabled: true
    className: tailscale
    hosts:
      - host: &host nl-home
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host

persistence:
  tmp:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /tmp
  udev: # This is used for access to Bluetooth.
    enabled: true
    type: hostPath
    hostPath: /run/udev
    globalMounts:
      - path: /run/udev
  dbus: # This is used for access to Bluetooth.
    enabled: true
    type: hostPath
    hostPath: /run/dbus
    globalMounts:
      - path: /run/dbus
        readOnly: true
  config:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: home-assistant-config-v2
    globalMounts:
      - path: /config
  secrets:
    enabled: true
    type: secret
    name: home-assistant-secrets
    globalMounts:
      - path: /config/secrets.yaml
        subPath: secrets.yaml
        readOnly: true
  configuration:
    enabled: true
    type: configMap
    name: home-assistant-configuration
    globalMounts:
      - path: /config/configuration.yaml
        subPath: configuration.yaml
        readOnly: true
      - path: /config/scenes.yaml
        subPath: scenes.yaml
        readOnly: true
      - path: /config/scripts.yaml
        subPath: scripts.yaml
        readOnly: true
  automations:
    enabled: true
    type: configMap
    name: home-assistant-automations
    globalMounts:
      - path: /config/automations
        readOnly: true
