---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace longhorn-system

resources:
  - longhorn-add-nixos-path.yaml
  # NOTE: apparently we cannot use globbing...
  # https://github.com/kubernetes-sigs/kustomize/issues/119
  - storageClasses/nvme-1-replicas.yaml
  - storageClasses/nvme-2-replicas.yaml
  - storageClasses/nvme-3-replicas.yaml
  - storageClasses/nvme-encrypted-2-replicas.yaml
  - storageClasses/nvme-encrypted-3-replicas.yaml
  - recurringJobs/backup-24h.yaml
  - recurringJobs/snapshot-6h.yaml

generators:
  - ksops.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.10.1
    releaseName: longhorn
    namespace: *namespace
    includeCRDs: true
    valuesFile: values.yaml
