---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace democratic-csi

generators:
  - ksops.yaml

helmCharts:
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts
    version: 0.15.0
    releaseName: truenas-nfs
    namespace: *namespace
    valuesFile: values.yaml
