# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: truenas-nfs-driver-config
    namespace: democratic-csi
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:3I9Io9qe6/VaD4f14QaFSo27ghRndVJk5Ii2CKQjURdh65jnQWzVFimCagGuIm/724lsGrIoXIPOr4Lr51CTyD6UzA/3/9PpEnk+MAHfSKLA37a/YFJY3OPsEZtTrezxCvp9lkeX8zKsX/eMh4UbAPLU5jEy5scxDKNRkbMhiwDbGK25n5mn5LJ41VsVqbW8Wiqyg10UTALdc2JCSHvdK91j9fgY51EmWimNJhJDSPPK8xkEImUckTNd4bL25fufXxqc8Nxv0+I5dhI3tk/2LBdj+Pbotl4l3g2lUDcl0Co8/uMxwcSC6g4utn2BI7/fgZrwjOjwiEkoh2mlo3MqwP6ltQqp6ekKS7YAs1Zxbum6+Uu6rO8DvF09sR15ohSHRySWXU+I8ZfONAtYf1XV8e6PVmkMXxM6SegkyqTI+88Yw3k1Ut43kdflfSK/4HqKJ3rrmbmB8NhogkdtiyzCAwxIhEqrkgNzbrbdvQjgwGuXZzcGcrmu3PBQOGKeCTdSpkvKsOOcDsjIBnpJLEBcS/SBSNotX55MWS3lrk8pWaLdTSKy9rNJKyZLGfYWfQAKVmoBQ7AGCjHV6nU/H1q4+r+yBL1d7cI1vI+7tPKXlBRd6WI4+xMZCMG61ry6y1xpGBYTic8DFVRg+x7lXdpC/+HhVzLNyfxkkTZzgUqPGQnvZF2svkj9/KzXncApXTpWQLCMl3POOz9AjMFhijX1mzXBtYwHp5zqjVfEOutmi+/J/qlKXpxhKWNjgvy7LNmrnkYebaE0behguGky0CY4tNAPuMUo2o6x11Kp0sw2rj5P3n0USvonsUYskOL1hLc2Rr5+kregWnbReO7JL7V+XQQgWL8TodhP5otbAalDtYMsE8uUaUQp2Bqn4HSU4lOLVWC/cE+HqY4t7qVMfW4xDJ9IzVCtrv8lAg8VpgNaQySvSOBGXcFO6RtFfe+JtgbdpEH8/RcXAp72dtT3lK+pbZ2x8nz2dz8VTYAV7XB1Tb2Q1WsGjw6+dlAk0Np0Bj/4LLXU1JH4JLcwVLvkmuvm3DOr0qjwdj7b+F6xnSeBKmDwmEx1BC8WERGayvAocQ==,iv:8zRraBVGeHo4T9Udk60jHf8figfnWBa3rlfoC7BR+z4=,tag:xBVjga4GhhV5SpAdMkV0Gg==,type:str]
sops:
    age:
        - recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhelh1eWhHQWR0OHBSQkJT
            eTZMbUc4L2dhc1V2dlF0aTBBQldNWkt1eEFNCmFNSHVsVzF6bHZBS1Era21pdWVG
            c0xza1RJZTVJNm0yWUdaRmpxdFMyK0kKLS0tIHRJNDUyRVIzZmE4VjVuNk1kMTVi
            cjV0L2NYTHhtSFlJZjV4Q0xuNThHZmMKj+wMGhQysomw5eZfG/7EcHe21oKVnU5s
            UMn09pOMhAkYTT/AxVYZPNFeEQEleM8cf+wCcxwBLpTilE7fPW2A1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T10:54:42Z"
    mac: ENC[AES256_GCM,data:GoGBjsOBP3jZTvyhFKEYQCRBR1xStFbQULtTYGuLmDVc451kxRcRUaG/3ctKpNpcHXMRPJsWGEZUyBz3F1IECPvRcTLqUgBvx28n7OjYJl3WK/wl0fW+KLKhrxDp+7QTsAWo9XtaeZAe/50H3m7ZNXkktUKOtKDT9tZvepbTuVY=,iv:/VtN3uFEYqJ5K3Lkkv8ucGJ98iATfQb9rZ2AgukOXao=,tag:qSQba6NhdzKu4HuYeIFcAA==,type:str]
    pgp:
        - created_at: "2025-11-24T10:52:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf+IGkTTBpIOyFaVirLlk2EvCVVpuodNlNWjo0iTmobjJ3A
            om7PWM9dudi8c1n6B9TPXWmWwxkzKCYUdAjXy3BnWUm31FNMvCHdOEtt0FJw15d3
            y1dYdaHzWd3K9yx2ZO3m/GM/1eIVMavm2vcYAxdkJsVzkzZ6ly06ft++Le5HIHzn
            wJXpXxKA4hUCXUopTCPl5z1f+KFlsBkTiMkvlMHn7Z5sdl9NxVaxTM5LRiqfMhRm
            BGXrwP+ZUvVT6ArZnffXs7VJSNgQcTZZqBUiCHZYlegJofmugbB2rZXzquuK1Jrw
            WwGC9eWGz8H4al94s163zczx2o3+H435kXxNeZgNdAf/VkCXkdhlwIy29D+4q0nV
            V7DZJc6CRhwuu0UA6dW5kdW61xrrxO62WptiXVjpL8lECwI//zjy5OGWlqAWDhUp
            6FudtOO/T3DYuAnw2P5/ZwhY5kmxxtcU0Zrzge4gTTvBnpQu/fRRu9NVTznSjva4
            RWX8YPrQ8XACQhK3HqYZlzgmzC7rW8TfDoYCJuAzpO7FPAixvmJXUDHp97WxdbXX
            tp9P6+NIfpfZq4RrF7Iehs+/L5b1EJNtVJV0DoSGrKsdE563br3PqyZ6B9A+/oQU
            zmvqnbu3J4Ka3PtutmiDgmZXy7leKMcHaDk08DB3xZ8szbgxO13ChHk09m+/hPED
            LtJcAfYpaUu3m0SZwct8UTTqiPVtOdV0hGqK7Q7+FlvOcKsA3HVozt/490l2DAZ0
            qKSPcgsj3bzmln78HG4BlSsIrMD3wA6H1Zy6h4yui2IK7GimjE4e8Mfnq9UL/sE=
            =XJWt
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
