---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace kube-system

helmCharts:
  - name: intel-device-plugins-operator
    repo: https://intel.github.io/helm-charts/
    version: 0.34.1
    releaseName: intel-device-plugins-operator
    namespace: *namespace
    includeCRDs: true
  - name: intel-device-plugins-gpu
    repo: https://intel.github.io/helm-charts/
    version: 0.34.1
    releaseName: intel-device-plugins-gpu
    namespace: *namespace
    includeCRDs: true
    valuesInline:
      sharedDevNum: 4
      nodeFeatureRule: true
