---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace telemetry

resources:
  - victorialogs-data.yaml
# helmCharts:
#   - name: victoria-logs-single
#     repo: https://victoriametrics.github.io/helm-charts/
#     version: 0.11.23
#     releaseName: victorialogs
#     namespace: *namespace
#     includeCRDs: true
#     valuesFile: values.yaml
