# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: telemetry
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:pQrAJi6/A4E961KxTsxSHUxRGm2FnQ1pLTFd53333aQApl7KxFtpkfww+T9UUpt82csai11LUc5+RGfs7wmWS95+4LFLJTMD,iv:3gwS6qDhrobnghfaoTEY6jyqM+FI7LeEARTrDw5dJSE=,tag:En72L0NWup7/ph2FlB+/oQ==,type:str]
sops:
    age:
        - recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESEQ5K0hUbklKa3YxWTRh
            QmFwTHM4amJZV2R4L2g2a0E5b0JlNUsxMVFVCkRVSjJiRURqMUdXLzdQTS9kaGpJ
            eGZNL3pIaVo5K0hTSkxCYjg0d0NJeFEKLS0tIE5aMWNmSmRUNC9ZRU1XT0tqaGhm
            QTRzUU5GSHpyVU9tdXVqQ1lTUFN2WkUKIcjgvY+7mOHz7r8NmPYsCZ25+JK1yiXJ
            dgiJYujlKQtCdj5/GAn2qtTfuLqNaGcV+FE0F6k0N+RHomWb6mN5ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T11:59:59Z"
    mac: ENC[AES256_GCM,data:aqxp8LKQxgzPRzxa3lJNNl11uZiPv6xfopNY1GASZRnZJnZidqPYM+/EGhJ1kVnoWn/YPxvKLGdoAPHu9cLgRMjyF5fIGFvhfcVuiNNPnkrxPh5184Uh8Mv9PigD8HH9eIhAy0dImZYGWlwyxCmrxWG58vE0ILLHvwgXXZlNFLQ=,iv:zyYswn3w/qeK42xlTNrvVvQ0jIIzgYDuGaYjwX1zW44=,tag:ktu0sI5PI2pPPCbeHnF/bg==,type:str]
    pgp:
        - created_at: "2025-11-24T11:59:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf8COMbWXbKIvOcr83cjH67plM5m9FQseRAJWUDwOSxcivW
            YXDqctZ52dWMkuU/ZHF2qWDogCGl+DaYuQrTsbNpJHrNgLaj4pa1w3qU4Ttg2xDe
            9BsY+jDBFSqvQUbUvi762EtP4AGRp9efiQHxW6CycGRD+3u20tH+qYCt/4oNcP9v
            uqQLGax7/1OzfJL4s8TeQdgevwvDu2ny1F71L5PdTvoLFW6hnEJldYg5C9WINLfN
            auYFkd2gd9g4qJt2MUSucGvasYp8fcT7mZhnbbOKrmmnDb68trTfe/8aSi+rBHAc
            1dxb6q1kqqoYLP9nXo9l54AbgPHo+3BTCiK07L9F4Af/Utzw9EuAcNYkSU4mnKoH
            j4w7cCKJfpfLIismcPFjOIPH9Z7l4oW8lQiq6EbUUlhVOz18EJlBwKSrWqL9defr
            iGSQs/ZWNdxdXjwFTkxOjMeLiV07LfaIGCVIy4fuLLCvE4XtJCtUiDV6J28HiYz3
            rSJ8pMBPjook/Aja7H6phMa54zK3guuy+8IXrMly3o3xNTV9iCnaQUaSKRr7OLns
            sxoWkYk3vnQV19zIRxBEkmvQghcr4WVhoL4noUAGxi/RxT74vY9lfyBvS+A4QDar
            tfzQ95cHhsJBc7Hc2zpWteNJeRyzw4WlkjOWJCxlOxLHahBRFXARFq+BFghleGIK
            ptJeATdZztluwMKcQeU5ysY1ErpMNoaK4HjApHrpF8brUDleJDu5Jo45ceL2PONW
            e/WI8nSoEQQ/WGuwg8VztmfEf8Pxta58EUZtwydxWRAalbcGEKGZU+LEiF6/BXqg
            Yw==
            =Pyn/
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
