---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: grafana-secrets-generator
  namespace: telemetry
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./grafana-secrets.enc.yaml
