---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace media

# resources:
#   - persistentvolumeclaims.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.4.0
    releaseName: bazarr
    namespace: *namespace
    valuesFile: values.yaml
