---
default_config:

logger:
  default: info
  logs:
    custom_components.auth_oidc: debug
    custom_components.xiaomi_cloud_map_extractor: debug

http:
  cors_allowed_origins:
    - https://nl-home.tail2ff90.ts.net
  use_x_forwarded_for: true
  trusted_proxies:
    - "127.0.0.1"
    - "::1"
    - "10.0.0.0/8" # LAN subnet
    - "100.0.0.0/8" # Tailnet

auth_oidc:
  display_name: "Authelia"
  client_id: !env_var HASS_OAUTH_CLIENT_ID
  client_secret: !env_var HASS_OAUTH_CLIENT_SECRET
  discovery_url: "https://idp.cianfr.one/.well-known/openid-configuration"
  id_token_signing_alg: "RS256"
  features:
    automatic_user_linking: true
    automatic_person_creation: true
  claims:
    display_name: name
    username: preferred_username
    groups: groups
  roles:
    admin: home-admin
    user: home-member

automation: !include automations.yaml # Required for the UI automations to work
script: !include scripts.yaml
scene: !include scenes.yaml

input_datetime:
  sleeping_time:
    name: Sleeping time
    has_date: false
    has_time: true
    icon: mdi:bed-clock
  wakeup_time:
    name: Wake up time
    has_date: false
    has_time: true
    icon: mdi:sun-clock
  coffee_machine_turnon_time:
    name: Coffee Machine turn-on time
    has_date: false
    has_time: true
    icon: mdi:coffee-maker

input_select:
  home_mode:
    name: Home Mode
    options:
      - Home # Someone is at home, normal working conditions
      - Away # Nobody is at home (other than Luna perhaps)
      - Sleeping # Time to sleep and be quiet, no disturbances
      - Vacation # We are away from home for an extended period of time
    icon: mdi:home-analytics

input_boolean:
  enable_litter_robot_vacuuming:
    name: Enable automatic vacuuming around the Litter Robot
    icon: mdi:robot-vacuum
  turn_on_coffee_machine:
    name: Turn on the Coffee Machine in the morning
    icon: mdi:coffee-maker

input_button:
  vacuum_around_litter_robot:
    name: Vacuum around Litter Robot
    icon: mdi:robot-vacuum

input_number:
  litter_robot_waste_drawer_level_notification:
    name: Litter Robot waste drawer fill percentage notification
    mode: slider
    icon: mdi:trash-can
    # initial: 20 # NOTE(ar3s3ru): disabled to avoid value resets at restart
    min: 10
    max: 100
    step: 5
    unit_of_measurement: "%"
  # TODO(ar3s3ru): still need to implement this automation,
  # it'll likely require a intermediate state update (e.g. next date -> notify -> update next date)
  litter_robot_days_notification_interval:
    name: Litter Robot days interval notification
    mode: slider
    icon: mdi:calendar-clock
    # initial: 3 # NOTE(ar3s3ru): disabled to avoid value resets at restart
    min: 1
    max: 7
    step: 1
    unit_of_measurement: "days"

template:
  - binary_sensor:
      - name: Toilet Occupancy
        # NOTE: using toilet_switch since it is more reliable and faster than the toilet_light.
        state: >
          {{ is_state('switch.toilet_switch', 'on') }}
        icon: >
          {% if is_state('binary_sensor.toilet_occupancy', 'on') %}
            mdi:toilet
          {% else %}
            mdi:toilet-outline
          {% endif %}

automation toilet: !include automations/toilet.yaml
automation home-mode: !include automations/home.yaml
automation vacuum: !include automations/vacuum.yaml
automation litter-robot: !include automations/litter-robot.yaml
automation kitchen: !include automations/kitchen.yaml
